# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT27_week6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT27_week6

pod 'Alamofire', '~> 5.2.2'
end
